// <auto-generated />
namespace PressMachineServices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_press_name_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_press_name_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201810021711422_change_press_name_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
